-------------------------------------------------------------------------------------------------------------------------------------------------------------
-- configuration file for EW Script 2.02 Plugin
--
-- This configuration is tailored for a mission generated by DCS Retribution
-- see https://github.com/dcs-retribution/dcs-retribution
-------------------------------------------------------------------------------------------------------------------------------------------------------------


-- EW Script 2.02 Plugin - Configuration
if dcsRetribution then
    -- retrieve specific options values
    if dcsRetribution.plugins then
        if dcsRetribution.plugins.ewrj then
            env.info("DCS Retribution | EW Script 2.02 - Setting Up")
            ewrj_options.OFFENSIVE_POWER = dcsRetribution.plugins.ewrj.OFFENSIVE_POWER
            ewrj_options.DEFENSIVE_POWER = dcsRetribution.plugins.ewrj.DEFENSIVE_POWER
            ewrj_options.MISSILE_JAM_SCALE = dcsRetribution.plugins.ewrj.MISSILE_JAM_SCALE
            ewrj_options.DEBUG = dcsRetribution.plugins.ewrj.DEBUG
            ewrj_options.DEBUG_OFFENSIVE = dcsRetribution.plugins.ewrj.DEBUG_OFFENSIVE
            ewrj_options.DEBUG_DEFENSIVE = dcsRetribution.plugins.ewrj.DEBUG_DEFENSIVE
            ewrj_options.DEBUG_ADVANCED = dcsRetribution.plugins.ewrj.DEBUG_ADVANCED
            env.info("[DEBUG EW SETUP] Offensive Power = "..ewrj_options.OFFENSIVE_POWER)
            env.info("[DEBUG EW SETUP] Defensive Power = "..ewrj_options.DEFENSIVE_POWER)
        end
    end
end
