local unitPayloads = {
	["name"]="vwv_o-1",
	["payloads"]=
	{
		[1]=
		{
			["displayName"]="Retribution CAS",
			["name"]="Retribution CAS",
			["pylons"]=
			{
				[1]=
				{
					["CLSID"]="{LAU68_FFAR_MK5HEAT}",
					["num"]=1
				},
				[2]=
				{
					["CLSID"]="{LAU68_FFAR_MK5HEAT}",
					["num"]=4
				},
				[3]=
				{
					["CLSID"]="{3xM8_ROCKETS_IN_TUBES}",
					["num"]=2
				},
				[4]=
				{
					["CLSID"]="{3xM8_ROCKETS_IN_TUBES}",
					["num"]=3
				}
			},
			["tasks"]=
			{
				[1]=31
			}
		},
		[2]=
		{
			["displayName"]="Retribution BAI",
			["name"]="Retribution BAI",
			["pylons"]=
			{
				[1]=
				{
					["CLSID"]="{LAU68_FFAR_MK5HEAT}",
					["num"]=1
				},
				[2]=
				{
					["CLSID"]="{LAU68_FFAR_MK5HEAT}",
					["num"]=4
				},
				[3]=
				{
					["CLSID"]="{3xM8_ROCKETS_IN_TUBES}",
					["num"]=2
				},
				[4]=
				{
					["CLSID"]="{3xM8_ROCKETS_IN_TUBES}",
					["num"]=3
				}
			},
			["tasks"]=
			{
				[1]=32,
				[2]=33
			}
		},
		[3]=
		{
			["displayName"]="Retribution Strike",
			["name"]="Retribution Strike",
			["pylons"]=
			{
				[1]=
				{
					["CLSID"]="{LAU68_FFAR_MK5HEAT}",
					["num"]=1
				},
				[2]=
				{
					["CLSID"]="{LAU68_FFAR_MK5HEAT}",
					["num"]=4
				},
				[3]=
				{
					["CLSID"]="{3xM8_ROCKETS_IN_TUBES}",
					["num"]=2
				},
				[4]=
				{
					["CLSID"]="{3xM8_ROCKETS_IN_TUBES}",
					["num"]=3
				}
			},
			["tasks"]=
			{
				[1]=32,
				[2]=33
			}
		},
		[4]=
		{
			["displayName"]="Retribution Armed Recon",
			["name"]="Retribution Armed Recon",
			["pylons"]=
			{
				[1]=
				{
					["CLSID"]="{LAU68_FFAR_MK5HEAT}",
					["num"]=1
				},
				[2]=
				{
					["CLSID"]="{LAU68_FFAR_MK5HEAT}",
					["num"]=4
				},
				[3]=
				{
					["CLSID"]="{3xM8_ROCKETS_IN_TUBES}",
					["num"]=2
				},
				[4]=
				{
					["CLSID"]="{3xM8_ROCKETS_IN_TUBES}",
					["num"]=3
				}
			},
			["tasks"]=
			{
				[1]=32,
				[2]=33
			}
		}
	},
	["unitType"]="vwv_o-1"
}
return unitPayloads