-- configuration file for Moose's Autolase Plugin
--
-- This configuration is tailored for a mission generated by DCS Retribution
-- see https://github.com/dcs-retribution/dcs-retribution
-------------------------------------------------------------------------------------------------------------------------------------------------------------


-- Autolase plugin - configuration
if dcsRetribution then
    -- retrieve specific options values
    if dcsRetribution.plugins then
        if dcsRetribution.plugins.Autolase then
            env.info("DCSRetribution|MOOSE Autolase plugin - Setting Up")
            --JTAC Alpha
            Moose_Autolase_options.JtacAlphaSmoke = dcsRetribution.plugins.Autolase.JtacAlphaSmoke
            Moose_Autolase_options.JtacAlphaUHF = dcsRetribution.plugins.Autolase.JtacAlphaUHF
            Moose_Autolase_options.JtacAlphaVHF = dcsRetribution.plugins.Autolase.JtacAlphaVHF
            Moose_Autolase_options.JtacAlphaRadiusNM = dcsRetribution.plugins.Autolase.JtacAlphaRadiusNM
            --JTAC Bravo
            Moose_Autolase_options.JtacBravoSmoke = dcsRetribution.plugins.Autolase.JtacBravoSmoke
            Moose_Autolase_options.JtacBravoUHF = dcsRetribution.plugins.Autolase.JtacBravoUHF
            Moose_Autolase_options.JtacBravoVHF = dcsRetribution.plugins.Autolase.JtacBravoVHF
            Moose_Autolase_options.JtacBravoRadiusNM = dcsRetribution.plugins.Autolase.JtacBravoRadiusNM
        end
    end
end
