-- configuration file for Soundhandler Plugin
--
-- This configuration is tailored for a mission generated by DCS Retribution
-- see https://github.com/dcs-retribution/dcs-retribution
-------------------------------------------------------------------------------------------------------------------------------------------------------------


-- Autolase plugin - configuration
if dcsRetribution then
    -- retrieve specific options values
    if dcsRetribution.plugins then
        if dcsRetribution.plugins.Soundhandler then
            env.info("------DCSRetribution|Soundhandler plugin - Setting Up------")
            Soundhandler_options.SoundsToGroupOnly = dcsRetribution.plugins.Soundhandler.SoundsToGroupOnly
            Soundhandler_options.ShipSamSounds = dcsRetribution.plugins.Soundhandler.ShipSamSounds
            Soundhandler_options.RedShootingSounds = dcsRetribution.plugins.Soundhandler.RedShootingSounds
            Soundhandler_options.Debug = dcsRetribution.plugins.Soundhandler.Debug
        end
    end
end
