-------------------------------------------------------------------------------------------------------------------------------------------------------------
-- configuration file for Splash Damage 3.4.2 Plugin
--
-- This configuration is tailored for a mission generated by DCS Retribution
-- see https://github.com/dcs-retribution/dcs-retribution
-------------------------------------------------------------------------------------------------------------------------------------------------------------


-- SD2 plugin - configuration
if dcsRetribution then
    -- retrieve specific options values
    if dcsRetribution.plugins then
        if dcsRetribution.plugins.splashdamage3 then
            env.info("DCSRetribution|Splash Damage 3.4.2 plugin - Setting Up")
            splash_damage_options.game_messages = dcsRetribution.plugins.splashdamage3.game_messages
            splash_damage_options.debug = dcsRetribution.plugins.splashdamage3.debug
            splash_damage_options.weapon_missing_message = dcsRetribution.plugins.splashdamage3.weapon_missing_message
            splash_damage_options.enable_radio_menu = dcsRetribution.plugins.splashdamage3.enable_radio_menu
            splash_damage_options.wave_explosions = dcsRetribution.plugins.splashdamage3.wave_explosions
            splash_damage_options.larger_explosions = dcsRetribution.plugins.splashdamage3.larger_explosions
            splash_damage_options.use_dynamic_blast_radius = dcsRetribution.plugins.splashdamage3.use_dynamic_blast_radius
            splash_damage_options.dynamic_blast_radius_modifier = dcsRetribution.plugins.splashdamage3.dynamic_blast_radius_modifier / 100
            splash_damage_options.damage_model = dcsRetribution.plugins.splashdamage3.damage_model
            splash_damage_options.static_damage_boost = dcsRetribution.plugins.splashdamage3.static_damage_boost
            splash_damage_options.overall_scaling = dcsRetribution.plugins.splashdamage3.overall_scaling / 100
            splash_damage_options.unit_disabled_health = dcsRetribution.plugins.splashdamage3.unit_disabled_health
            splash_damage_options.unit_cant_fire_health = dcsRetribution.plugins.splashdamage3.unit_cant_fire_health
            splash_damage_options.infantry_cant_fire_health = dcsRetribution.plugins.splashdamage3.infantry_cant_fire_health
            splash_damage_options.cluster_enabled = dcsRetribution.plugins.splashdamage3.cluster_enabled
            splash_damage_options.rocket_multiplier = dcsRetribution.plugins.splashdamage3.rocket_multiplier
            splash_damage_options.shipRadarDamageEnable = dcsRetribution.plugins.splashdamage3.shipRadarDamageENable
            splash_damage_options.oca_aircraft_damage_boost = dcsRetribution.plugins.splashdamage3.oca_aircraft_damage_boost
        end
    end
end
