-------------------------------------------------------------------------------------------------------------------------------------------------------------
-- configuration file for BigEye EWR Plugin
--
-- This configuration is tailored for a mission generated by DCS Retribution
-- see https://github.com/dcs-retribution/dcs-retribution
-------------------------------------------------------------------------------------------------------------------------------------------------------------


-- BigEye EWR Plugin - configuration
if dcsRetribution then
    -- retrieve specific options values
    if dcsRetribution.plugins then
        if dcsRetribution.plugins.bigeye then
            env.info("DCSRetribution|BigEye EWR - Setting Up")
            EWR.displayMessageTime = dcsRetribution.plugins.bigeye.displayMessageTime
            EWR.highReportFrequencyPreference = dcsRetribution.plugins.bigeye.highReportFrequencyPreference
            EWR.defaultReportFrequencyPreference = dcsRetribution.plugins.bigeye.defaultReportFrequencyPreference
            EWR.lowReportFrequencyPreference = dcsRetribution.plugins.bigeye.lowReportFrequencyPreference
            EWR.gciReportFrequency = dcsRetribution.plugins.bigeye.gciReportFrequency
            EWR.defaultEnableReportPreference = dcsRetribution.plugins.bigeye.defaultEnableReportPreference
            EWR.maxReportUnits = dcsRetribution.plugins.bigeye.maxReportUnits
            EWR.isAvailableNCTR = dcsRetribution.plugins.bigeye.isAvailableNCTR
            EWR.blueHasDLINK = dcsRetribution.plugins.bigeye.blueHasDLINK
            EWR.blueHasRWR = dcsRetribution.plugins.bigeye.blueHasRWR
            EWR.blueHasIRST = dcsRetribution.plugins.bigeye.blueHasIRST
            EWR.redHasDLINK = dcsRetribution.plugins.bigeye.redHasDLINK
            EWR.redHasRWR = dcsRetribution.plugins.bigeye.redHasRWR
            EWR.redHasIRST = dcsRetribution.plugins.bigeye.redHasIRST
            EWR.reportUnitNameNATO = dcsRetribution.plugins.bigeye.reportUnitNameNATO
        end
    end
end
