---
name: Bug report
description: >
  Use for any bug that happens after campaign generation. If the New Game wizard
  failed, use the "New Game wizard failed" template instead.
labels: ["Bug", "Priority Medium"]
body:
  - type: markdown
    attributes:
      value: >
        Before filing, please search the issue tracker to see if the issue has
        already been reported.
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Affected versions
      multiple: true
      description: >
        Select all DCS Retribution versions in which you have observed this bug.
        You do not need to test all of them, but the information is useful if
        you have it.


        If you do not see your version listed here you are on an old release
        that is not supported, and the bug may already be fixed in a newer
        release. Check that the bug still exists in a newer release before
        filing.


        If the bug was found in a test/development build, select "Test build" or "Development build"
        and provide a link to the applicable build in the field below.
      options:
        - v1.1
        - Test build
        - Development build
  - type: input
    attributes:
      label: Test/Development build
      description: A link to the test/development build, if applicable.
  - type: textarea
    attributes:
      label: Description
      description: >
        Describe the bug. What went wrong? What did you expect to happen
        instead? What steps should we take to reproduce the error? If an error
        dialog was shown, include the full text.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Save game and other files
      description: >
        Attach any files needed to reproduce the bug here. **A save game is
        required.** We typically cannot help without a save game (the
        `.retribution` file found in
        `%USERPROFILE%/Saved Games/DCS/Retribution/Saves`), so most bugs filed
        without saved games will be closed without investigation.


        Other useful files to include are:


        The Retribution log file. The log file is located at
        `<Retribution install directory>/logs/retribution.log`. The log often
        includes data about non-fatal errors that could be the root cause of the
        problem.


        The `retribution_nextturn.miz` or a track file. This should always be
        included for bugs where the mission was generated incorrectly or where
        the in-game AI is misbehaving.


        The `state.json` file for the most recently completed turn, located at
        `<Retribution install directory>/state.json`. This file is essential for
        investigating any issues with end-of-turn results processing.


        You can attach files to the bug by dragging and dropping the file
        into this text box. GitHub will not allow uploads of all file types, so
        attach a zip of the files if needed.
    validations:
      required: true
