---
name: Feature Request
description: >
  Suggest an idea for this project.
labels: enhancement
body:
  - type: markdown
    attributes:
      value: >
        Before filing, please search the issue tracker to see if this feature has already been requested.
        If requesting a DCS AI feature, check If reporting a DCS AI bug, 
        check https://github.com/dcs-retribution/dcs-retribution#dcs-bugs.
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: >
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: >
        A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: >
        Add any other context or screenshots about the feature request here.
