-------------------------------------------------------------------------------------------------------------------------------------------------------------
-- configuration file for Splash Damage 2 Plugin
--
-- This configuration is tailored for a mission generated by DCS Retribution
-- see https://github.com/dcs-retribution/dcs-retribution
-------------------------------------------------------------------------------------------------------------------------------------------------------------


-- SD2 plugin - configuration
if dcsRetribution then
    -- retrieve specific options values
    if dcsRetribution.plugins then
        if dcsRetribution.plugins.dismounts then
            env.info("DCSRetribution|DCS Dismounts plugin - Setting Up")

            --dismountsOptions.LeaveDeployed = dcsRetribution.plugins.dismounts.LeaveDeployed
            dismountsOptions.WWIIAssets = dcsRetribution.plugins.dismounts.WWIIAssets
            dismountsOptions.FrenchPack = dcsRetribution.plugins.dismounts.FrenchPack
            --dismountsOptions.TroopsFollowSlowTransport = dcsRetribution.plugins.dismounts.TroopsFollowSlowTransport
            dismountsOptions.GorgeousGeorgians = dcsRetribution.plugins.dismounts.GorgeousGeorgians
            --dismountsOptions.RandomizeRussianTroops = dcsRetribution.plugins.dismounts.RandomizeRussianTroops
            dismountsOptions.NoManpads = dcsRetribution.plugins.dismounts.NoManpads
            --dismountsOptions.WPNSitesAddMoreWPNToFreeVehicles = dcsRetribution.plugins.dismounts.WPNSitesAddMoreWPNToFreeVehicles

            mechanizeAll(nil)
        end
    end
end
