"""Load OSM-derived per-airport imagery offsets and runway geometry.

JSON files live under ``resources/airport_imagery/<terrain>.json`` and are
generated by ``scripts/derive_airport_imagery_offsets.py``. This module
provides a lazy cached loader and lightweight accessors used by:

* the basemap renderer — to translate Esri tile coverage by the per-airport
  imagery offset so the satellite overlays where DCS draws its markers,
* the threshold-marker computation — to place markers at the real runway
  endpoints from OSM rather than a hard-coded ±900 m from airport center.
"""

from __future__ import annotations

import json
import logging
import threading
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Dict, Optional

if TYPE_CHECKING:
    from dcs.terrain.terrain import Airport, Terrain

logger = logging.getLogger(__name__)

_RESOURCES_DIR = Path(__file__).resolve().parents[3] / "resources"
_IMAGERY_DIR = _RESOURCES_DIR / "airport_imagery"

# Terrain name in the JSON (matches DCS Terrain.name) -> records dict.
# A cached value of None marks a terrain known to have no JSON shipped,
# so repeat lookups for unsupported terrains don't keep probing the disk.
_cache: Dict[str, Optional["TerrainImagery"]] = {}
_cache_lock = threading.Lock()
_CACHE_MISS = object()


@dataclass(frozen=True)
class RunwayRecord:
    """One real-world runway from OSM.

    Headings are in degrees, true-north, 0-360. ``length_m`` is the OSM
    great-circle length between the two endpoints. ``heading_deg`` is the
    direction from endpoint A to endpoint B.
    """

    ref: Optional[str]
    surface: Optional[str]
    status: str
    osm_way_id: int
    length_m: float
    heading_deg: float
    midpoint_lat: float
    midpoint_lng: float
    endpoint_a_lat: float
    endpoint_a_lng: float
    endpoint_b_lat: float
    endpoint_b_lng: float

    @property
    def half_length_m(self) -> float:
        return self.length_m / 2.0

    def matches_heading(
        self, dcs_heading_deg: float, tolerance_deg: float = 15.0
    ) -> bool:
        """True if this runway's heading matches `dcs_heading_deg` either way.

        OSM stores the way's direction (A -> B); DCS exposes both approach
        headings (e.g. 250 for RWY 25 and 70 for RWY 07). A runway matches
        whether DCS asks about either end, hence checking both heading and
        heading+180.
        """
        a = (self.heading_deg - dcs_heading_deg + 540.0) % 360.0 - 180.0
        b = (self.heading_deg - (dcs_heading_deg + 180.0) + 540.0) % 360.0 - 180.0
        return abs(a) <= tolerance_deg or abs(b) <= tolerance_deg

    def threshold_for_approach(
        self, approach_heading_deg: float
    ) -> tuple[float, float]:
        """Return ``(lat, lng)`` of the runway threshold for this approach.

        Aircraft landing at heading ``approach_heading_deg`` cross the
        threshold at the runway end opposite their flight direction. We
        pick whichever OSM endpoint (A or B) is closer to the
        ``approach_heading + 180`` direction from the midpoint.
        """
        threshold_dir = (approach_heading_deg + 180.0) % 360.0
        # Direction from midpoint to B is `heading_deg`; to A is `heading_deg + 180`.
        diff_b = _angle_delta(self.heading_deg, threshold_dir)
        diff_a = _angle_delta((self.heading_deg + 180.0) % 360.0, threshold_dir)
        if abs(diff_b) <= abs(diff_a):
            return self.endpoint_b_lat, self.endpoint_b_lng
        return self.endpoint_a_lat, self.endpoint_a_lng


def _angle_delta(a: float, b: float) -> float:
    """Signed shortest angular difference a -> b in degrees, in [-180, 180]."""
    return ((b - a + 540.0) % 360.0) - 180.0


@dataclass(frozen=True)
class AirportImagery:
    """All OSM-derived data we have for one airport."""

    name: str
    imagery_offset_lat: float
    imagery_offset_lng: float
    runways: tuple[RunwayRecord, ...]
    elevation_m: Optional[float] = None
    elevation_source: Optional[str] = None

    def runway_for_heading(self, dcs_heading_deg: float) -> Optional[RunwayRecord]:
        """Pick the OSM runway whose heading matches `dcs_heading_deg`.

        Prefers ``status == "active"`` entries: a longer abandoned/disused
        strip adjacent to the live runway must not steal the threshold/
        imagery anchor. Falls back to non-active matches only when no
        active runway matches the heading. Within the chosen status tier,
        the longest match wins. Returns ``None`` if nothing matches
        within tolerance.
        """
        matches = [r for r in self.runways if r.matches_heading(dcs_heading_deg)]
        if not matches:
            return None
        active = [r for r in matches if r.status == "active"]
        return max(active or matches, key=lambda r: r.length_m)


@dataclass(frozen=True)
class TerrainImagery:
    """All airport records for one DCS terrain."""

    terrain: str
    by_airport_id: Dict[str, AirportImagery]

    def for_airport(self, airport: "Airport") -> Optional[AirportImagery]:
        """Look up by pydcs `airport.id`. Returns None if no entry exists."""
        return self.by_airport_id.get(str(airport.id))


def _cache_key(terrain_name: str) -> str:
    """Normalize so callers passing equivalent name variants share a cache slot.

    `_load_from_disk` resolves the JSON file via the same normalisation
    (lowercase + strip spaces + strip underscores); the cache uses the same
    derivation so a second call with a differently-spaced name is a hit, not
    a redundant disk read.
    """
    return terrain_name.lower().replace(" ", "").replace("_", "")


def load(terrain_name: str) -> Optional[TerrainImagery]:
    """Return the imagery record for ``terrain_name`` or None if not shipped.

    Cached after the first read. Safe to call from multiple threads.
    """
    key = _cache_key(terrain_name)
    with _cache_lock:
        cached = _cache.get(key, _CACHE_MISS)
        if cached is not _CACHE_MISS:
            return cached  # type: ignore[return-value]
        loaded = _load_from_disk(terrain_name)
        _cache[key] = loaded  # cache misses too — avoid disk re-probe
        return loaded


def _load_from_disk(terrain_name: str) -> Optional[TerrainImagery]:
    candidates = [
        terrain_name.lower(),
        terrain_name.lower().replace(" ", ""),
        terrain_name.lower().replace(" ", "_"),
    ]
    path: Optional[Path] = None
    for cand in candidates:
        p = _IMAGERY_DIR / f"{cand}.json"
        if p.exists():
            path = p
            break
    if path is None:
        logger.debug(
            "airport_imagery: no JSON for terrain %r in %s",
            terrain_name,
            _IMAGERY_DIR,
        )
        return None
    try:
        # Explicit UTF-8 — Windows defaults to the system locale (e.g.
        # cp1252) which fails on accented airport names like Simferopol
        # or Beslan and would otherwise drop the entire terrain via the
        # outer except.
        with path.open("r", encoding="utf-8") as f:
            raw = json.load(f)
    except Exception as exc:
        logger.warning(
            "airport_imagery: failed to read %s (%s); ignoring",
            path,
            exc,
        )
        return None

    by_id: Dict[str, AirportImagery] = {}
    for aid, rec in raw.get("airports", {}).items():
        # Parse each airport record independently. A malformed runway entry
        # (or any missing required key) used to escape the generator and
        # propagate up through `_load_from_disk` to the caller, silently
        # losing every other airport in the terrain. Skip the offender and
        # log instead so the rest of the terrain still loads.
        try:
            offset = rec.get("imagery_offset_deg")
            runways: list[RunwayRecord] = []
            for r in rec.get("runways", []):
                try:
                    runways.append(
                        RunwayRecord(
                            ref=r.get("ref"),
                            surface=r.get("surface"),
                            status=r.get("status", "active"),
                            osm_way_id=int(r["osm_way_id"]),
                            length_m=float(r["length_m"]),
                            heading_deg=float(r["heading_deg"]),
                            midpoint_lat=float(r["midpoint"]["lat"]),
                            midpoint_lng=float(r["midpoint"]["lng"]),
                            endpoint_a_lat=float(r["endpoint_a"]["lat"]),
                            endpoint_a_lng=float(r["endpoint_a"]["lng"]),
                            endpoint_b_lat=float(r["endpoint_b"]["lat"]),
                            endpoint_b_lng=float(r["endpoint_b"]["lng"]),
                        )
                    )
                except (KeyError, TypeError, ValueError) as exc:
                    logger.warning(
                        "airport_imagery: %s airport %s has malformed runway "
                        "entry %r (%s); skipping runway",
                        terrain_name,
                        aid,
                        r,
                        exc,
                    )
            ele_raw = rec.get("elevation_m")
            try:
                elevation_m = float(ele_raw) if ele_raw is not None else None
            except (TypeError, ValueError):
                elevation_m = None
            by_id[aid] = AirportImagery(
                name=rec.get("name", "?"),
                imagery_offset_lat=(offset or {}).get("lat", 0.0) or 0.0,
                imagery_offset_lng=(offset or {}).get("lng", 0.0) or 0.0,
                runways=tuple(runways),
                elevation_m=elevation_m,
                elevation_source=rec.get("elevation_source"),
            )
        except (KeyError, TypeError, ValueError) as exc:
            logger.warning(
                "airport_imagery: %s airport %s is malformed (%s); " "skipping entry",
                terrain_name,
                aid,
                exc,
            )
    return TerrainImagery(terrain=raw.get("terrain", terrain_name), by_airport_id=by_id)


def field_elevation_for_airport(
    terrain: Optional["Terrain"], airport: Optional["Airport"]
) -> Optional[float]:
    """Look up the OSM/DEM-derived field elevation (m AMSL) for an airport.

    Returns ``None`` when no JSON ships for the terrain, no entry matches
    the airport ID, or the matching entry's ``elevation_m`` is unset. Used
    by both the recon ATIS pipeline and the briefing page's QFE line so the
    two stay aligned if the lookup chain changes (e.g. matching airports
    via a different key in the future).
    """
    if airport is None or terrain is None:
        return None
    record = load(terrain.name)
    if record is None:
        return None
    entry = record.for_airport(airport)
    if entry is None:
        return None
    return entry.elevation_m


def _clear_cache() -> None:
    """Test hook — drop the in-memory cache."""
    with _cache_lock:
        _cache.clear()
