-------------------------------------------------------------------------------------------------------------------------------------------------------------
-- configuration file for Carsten's Arty Spotter Plugin
--
-- This configuration is tailored for a mission generated by DCS Retribution
-- see https://github.com/dcs-retribution/dcs-retribution
-------------------------------------------------------------------------------------------------------------------------------------------------------------


-- arty plugin - configuration
if dcsRetribution then
    -- retrieve specific options values
    if dcsRetribution.plugins then
        if dcsRetribution.plugins.arty then
            env.info("DCSRetribution|Carsten's Arty Spotter plugin - Setting Up")

            cg_arty_options.user_fireDelay = dcsRetribution.plugins.arty.user_fireDelay
            cg_arty_options.user_quantity = dcsRetribution.plugins.arty.user_quantity
            cg_arty_options.user_spread = dcsRetribution.plugins.arty.user_spread
            cg_arty_options.user_spottingDistance = dcsRetribution.plugins.arty.user_spottingDistance
        end
    end
end
