-------------------------------------------------------------------------------------------------------------------------------------------------------------
-- configuration file for the Wheelyjoe's Weapons Damage Mod updated by Ghosti to support cluster munitions
-- and ship radar effects.
--
-- This configuration is tailored for a mission generated by DCS Retribution
-- see https://github.com/dcs-retribution/dcs-retribution
-------------------------------------------------------------------------------------------------------------------------------------------------------------

-- SplashDamageClusters plugin - configuration
env.info("DCSRetribution|SplashDamageClusters plugin - configuration")

if dcsRetribution then
    env.info("DCSRetribution|SplashDamageClusters plugin - dcsRetribution")

    -- specific options
    local bdaMessages = false
    local clusterEffects = false
    local shipRadarDamage = false

    -- retrieve specific options values
    if dcsRetribution.plugins then
        env.info("DCSRetribution|SplashDamageClusters plugin - dcsRetribution.plugins")
    
        if dcsRetribution.plugins.splashdamageclusters then
            env.info("DCSRetribution|SplashDamageClusters plugin - dcsRetribution.plugins.SplashDamage")
            bdaMessages = dcsRetribution.plugins.splashdamageclusters.bdaMessages
            env.info(string.format("DCSRetribution|SplashDamageClusters plugin - bdaMessages = %s",tostring(bdaMessages)))

            clusterEffects = dcsRetribution.plugins.splashdamageclusters.clusterEffects
            env.info(string.format("DCSRetribution|SplashDamageClusters plugin - clusterEffects = %s",tostring(clusterEffects)))

            shipRadarDamage = dcsRetribution.plugins.splashdamageclusters.shipRadarDamage
            env.info(string.format("DCSRetribution|SplashDamageClusters plugin - shipRadarDamage = %s",tostring(shipRadarDamage)))
        end
    end
    
    -- actual configuration code    
    weaponDamage(bdaMessages, clusterEffects, shipRadarDamage)

end